ok

diff --git a/infra/docker/web/integration-test/docker-compose-test.yml b/infra/docker/web/integration-test/docker-compose-test.yml
--- a/infra/docker/web/integration-test/docker-compose-test.yml
+++ b/infra/docker/web/integration-test/docker-compose-test.yml
@@ -48,27 +48,27 @@ services:
   
     command: |
     
-      --interval=30s --timeout=30s --retries=5 \
-      curl --fail http://calkube:3000 || exit 1
+     
+      # curl --fail http://localhost:3000 || exit 1
   
      
           # echo "Waiting for the server to start..."
           #   sleep 120
 
-          #  for i in {1..60}; do
-          #     echo "Checking server health ($i/60)..."
-          #     response=$(curl -o /dev/null -s -w "%{http_code}" calkube:3000)
-          #     echo "HTTP Status Code: $response"
-          #     if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
-          #       echo "Server is healthy"
-          #       # Now, shutdown the server
-          #       kill $server_pid
-          #       exit 0
-          #     fi
-          #     sleep 1
-          #   done
+           for i in {1..60}; do
+              echo "Checking server health ($i/60)..."
+              response=$(curl -o /dev/null -s -w "%{http_code}" calkube:3000)
+              echo "HTTP Status Code: $response"
+              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+                echo "Server is healthy"
+                # Now, shutdown the server
+                kill $server_pid
+                exit 0
+              fi
+              sleep 1
+            done
         
-          #   echo "Server health check failed"
-          #   kill $server_pid
-          #   exit 1
+            echo "Server health check failed"
+            kill $server_pid
+            exit 1
     
