adjust

diff --git a/infra/docker/web/integration-test/docker-compose-test.yml b/infra/docker/web/integration-test/docker-compose-test.yml
--- a/infra/docker/web/integration-test/docker-compose-test.yml
+++ b/infra/docker/web/integration-test/docker-compose-test.yml
@@ -34,5 +34,19 @@ services:
       postgres:
         condition: service_healthy
     # run all your tests here against the calkube service
-    command:  curl --fail-with-body http://calkube:3000 || exit 1
+    command:  |
+     response=$(curl -o /dev/null -s -w "%{http_code}" calkube:3000 auth/login)
+              echo "HTTP Status Code: $response"
+              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+                echo "Server is healthy"
+                # Now, shutdown the server
+                kill $server_pid
+                exit 0
+              fi
+              sleep 1
+
+            echo "Server health check failed"
+            kill $server_pid
+            exit 1
+    #  curl --fail-with-body http://calkube:3000 || exit 1
     
