all

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -168,32 +168,32 @@ jobs:
           echo Testing image: "$TESTING_IMAGE"
           docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up --exit-code-from sut       
 
-      # - name: Test healthcheck in Docker Compose
-      #   # ghcr.io/${REPO}:"$GITHUB_RUN_ID"
-      #   run: |
-      #     # export TESTING_IMAGE=ghcr.io/chichicaleb/gitops-mono-repo:7364832710
-      #     # echo Testing image: "$TESTING_IMAGE"
-      #     docker run -e DATABASE_URL: postgresql://localUser:localPassword@localhost:5432/test --rm ghcr.io/chichicaleb/gitops-mono-repo:7364832710
+      - name: Test healthcheck in Docker Compose
+        # ghcr.io/${REPO}:"$GITHUB_RUN_ID"
+        run: |
+          # export TESTING_IMAGE=ghcr.io/chichicaleb/gitops-mono-repo:7364832710
+          # echo Testing image: "$TESTING_IMAGE"
+          docker run -e DATABASE_URL: postgresql://localUser:localPassword@localhost:5432/test  ghcr.io/chichicaleb/gitops-mono-repo:7364832710
           
-      #     echo "Waiting for the server to start..."
-      #       sleep 120
+          echo "Waiting for the server to start..."
+            sleep 120
 
-      #      for i in {1..60}; do
-      #         echo "Checking server health ($i/60)..."
-      #         response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
-      #         echo "HTTP Status Code: $response"
-      #         if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
-      #           echo "Server is healthy"
-      #           # Now, shutdown the server
-      #           kill $server_pid
-      #           exit 0
-      #         fi
-      #         sleep 1
-      #       done
+           for i in {1..60}; do
+              echo "Checking server health ($i/60)..."
+              response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
+              echo "HTTP Status Code: $response"
+              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+                echo "Server is healthy"
+                # Now, shutdown the server
+                kill $server_pid
+                exit 0
+              fi
+              sleep 1
+            done
         
-      #       echo "Server health check failed"
-      #       kill $server_pid
-      #       exit 1
+            echo "Server health check failed"
+            kill $server_pid
+            exit 1
         # env:
         #  DATABASE_URL: postgresql://localUser:localPassword@localhost:5432/test
 
