compose

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -149,12 +149,61 @@ jobs:
         run: |
               echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
 
+      - name: Copy env  
+        run: |
+          
+          cat .env >> $GITHUB_ENV
+          echo "DATABASE_HOST=localhost:5432" >> $GITHUB_ENV
+          eval $(sed -e '/^#/d' -e 's/^/export /' -e 's/$/;/' .env) ;
+
+      - name: Start database
+        run: |
+          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up -d database  
+
       - name: Test healthcheck in Docker Compose
         # ghcr.io/${REPO}:"$GITHUB_RUN_ID"
+       
         run: |
-          export TESTING_IMAGE=ghcr.io/chichicaleb/gitops-mono-repo:7372470516
-          echo Testing image: "$TESTING_IMAGE"
-          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up --exit-code-from sut
+        
+      
+          docker run --rm --network stack \
+            -p 3000:3000 \
+            -e DATABASE_URL=postgresql://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@database/${{ env.POSTGRES_DB }} \
+            -e NEXTAUTH_SECRET=${{ env.NEXTAUTH_SECRET }} \
+            -e CALENDSO_ENCRYPTION_KEY=${{ env.CALENDSO_ENCRYPTION_KEY }} \
+            ghcr.io/chichicaleb/gitops-mono-repo:7372470516 &
+              
+            server_pid=$!
+
+
+            echo "Waiting for the server to start..."
+            sleep 120
+
+            echo ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login
+        
+            for i in {1..60}; do
+              echo "Checking server health ($i/60)..."
+              response=$(curl -o /dev/null -s -w "%{http_code}" ${{ env.NEXT_PUBLIC_WEBAPP_URL }}/auth/login)
+              echo "HTTP Status Code: $response"
+              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+                echo "Server is healthy"
+                # Now, shutdown the server
+                kill $server_pid
+                exit 0
+              fi
+              sleep 1
+            done
+        
+            echo "Server health check failed"
+            kill $server_pid
+            exit 1
+        env:
+          NEXTAUTH_SECRET: 'EI4qqDpcfdvf4A+0aQEEx8JjHxHSy4uWiZw/F32K+pA='
+          CALENDSO_ENCRYPTION_KEY: '0zfLtY99wjeLnsM7qsa8xsT+Q0oSgnOL'
+        # run: |
+        #   export TESTING_IMAGE=ghcr.io/chichicaleb/gitops-mono-repo:7372470516
+        #   echo Testing image: "$TESTING_IMAGE"
+        #   docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up --exit-code-from sut
 
 
 
