all

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -165,21 +165,21 @@ jobs:
           echo Testing image: "$TESTING_IMAGE"
      
           
-          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up -d calcom 
+          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up --exit-code-from sut 
 
-          echo "Waiting for the server to start..."
-          sleep 60s
-          response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
-          if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
-                echo "Server is healthy"
+          # echo "Waiting for the server to start..."
+          # sleep 60s
+          # response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
+          # if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+          #       echo "Server is healthy"
                
-                exit 0
-              fi
-              sleep 1
+          #       exit 0
+          #     fi
+          #     sleep 1
 
-            echo "Server health check failed"
+          #   echo "Server health check failed"
            
-            exit 1
+          #   exit 1
 
 
 
diff --git a/infra/docker/web/integration-test/docker-compose-test.yml b/infra/docker/web/integration-test/docker-compose-test.yml
--- a/infra/docker/web/integration-test/docker-compose-test.yml
+++ b/infra/docker/web/integration-test/docker-compose-test.yml
@@ -52,5 +52,24 @@ services:
     depends_on:
       - database
   
+  sut:
+    image: "${TESTING_IMAGE}"
+    depends_on:
+      - database
+      - calcom
 
+    command: | 
+      echo "Waiting for the server to start..."
+          sleep 60s
+          response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
+          if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+                echo "Server is healthy"
+               
+                exit 0
+              fi
+              sleep 1
+
+            echo "Server health check failed"
+           
+            exit 1
     
