added

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -66,7 +66,7 @@ jobs:
 
 # # NEXT JOB #######################################################################   
   test-integration:
-    name: Integration tests in Compose
+    name: Integration test in Compose
     # needs: [build-test-image]
     runs-on: ubuntu-latest
     permissions:
@@ -100,21 +100,21 @@ jobs:
           export TESTING_IMAGE=ghcr.io/chichicaleb/gitops-mono-repo:7372470516
           echo Testing image: "$TESTING_IMAGE"
           
-          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up -d calcom 
+          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up  sut 
 
-          echo "Waiting for the server to be healthy..."
-          sleep 60s
+          # echo "Waiting for the server to be healthy..."
+          # sleep 60s
           
-          response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
+          # response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
 
-          if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
-          echo "Server is healthy"
-          exit 0
-          fi
+          # if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+          # echo "Server is healthy"
+          # exit 0
+          # fi
           
-          sleep 1
-          echo "Server health check failed"
-          exit 1
+          # sleep 1
+          # echo "Server health check failed"
+          # exit 1
 
 
 
