yes

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -163,9 +163,31 @@ jobs:
         run: |
           export TESTING_IMAGE=ghcr.io/chichicaleb/gitops-mono-repo:7372470516
           echo Testing image: "$TESTING_IMAGE"
-         
-          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up --exit-code-from sut
+          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up -d database  
+          
+          docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up --exit-code-from calcom
 
+
+            echo "Waiting for the server to start..."
+            sleep 120
+
+        
+            for i in {1..60}; do
+              echo "Checking server health ($i/60)..."
+              response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
+              echo "HTTP Status Code: $response"
+              if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+                echo "Server is healthy"
+                
+                kill $server_pid
+                exit 0
+              fi
+              sleep 1
+            done
+        
+            echo "Server health check failed"
+            kill $server_pid
+            exit 1
 
 
 
