added

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -13,17 +13,11 @@ jobs:
   # build-test-image:
   #   name: Build Image for Testing
   #   runs-on: ubuntu-latest
-
   #   permissions:
-    
-  #     contents: read
-      
-  #     packages: write # needed to push docker image to ghcr.io
-
+  #    contents: read
+  #    packages: write 
   #   steps:
       
-    
-
   #     - name: checkout
   #       uses: actions/checkout@v4
 
@@ -32,28 +26,18 @@ jobs:
   #       uses: docker/metadata-action@v5
   #       with:
   #        images: ghcr.io/${{ github.repository }}
-
   #        tags: |
   #           ${{ github.run_id }}
    
-
-
- 
-        
-
-        
-
   #     - name: create custom network
   #       run : |
   #         docker network create stack
-
 
   #     - name: Set up Docker Buildx
   #       uses: docker/setup-buildx-action@v3
   #       with:
   #         driver-opts: |
   #           network=stack
-
 
   #     - name: Login to Docker Hub
   #       uses: docker/login-action@v3
@@ -68,64 +52,26 @@ jobs:
   #         username: ${{ github.repository_owner }}
   #         password:  ${{ secrets.GITHUB_TOKEN }}
 
-        
   #     - name: Build and Push to GHCR
   #       uses: docker/build-push-action@v5
   #       with:
   #         context: ./
   #         file: infra/docker/web/Dockerfile
   #         push: true
-          
   #         tags: ${{ steps.docker_meta.outputs.tags }}
-          
-         
-          
   #         cache-from: type=gha
   #         cache-to: type=gha,mode=max
   #         platforms: linux/amd64
          
-            
-
-    
-#  # NEXT JOB #######################################################################   
-  # test-unit:
-  #   name: Unit tests in Docker
-  #   needs: [build-test-image]
-  #   runs-on: ubuntu-latest
-
-  #   permissions:
-  #     packages: read
-      
-  #   steps:
-      
-  #     - name: Login to ghcr.io registry
-  #       uses: docker/login-action@v3
-  #       with:
-  #         registry: ghcr.io
-  #         username: ${{ github.repository_owner }}
-  #         password:  ${{ secrets.GITHUB_TOKEN }}
-
-  #     - name: Downcase repo name
-  #       run: |
-  #        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
-      
-  #     - name: Unit Testing in Docker
-  #       run: docker run --rm ghcr.io/${REPO}:"$GITHUB_RUN_ID" sh -c "yarn test"
-
-
-
 
 # # NEXT JOB #######################################################################   
   test-integration:
     name: Integration tests in Compose
     # needs: [build-test-image]
     runs-on: ubuntu-latest
-
     permissions:
       packages: read
       contents: read
-     
-
     steps:
 
       - name: Checkout git repo
@@ -145,43 +91,30 @@ jobs:
           password:  ${{ secrets.GITHUB_TOKEN }}
 
       - name: Downcase repo name
-        
         run: |
               echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
             
-
-          
-
- 
-        
-
-          
-
       - name: Test healthcheck in Docker Compose
         # ghcr.io/${REPO}:"$GITHUB_RUN_ID"
-        
         run: |
           export TESTING_IMAGE=ghcr.io/chichicaleb/gitops-mono-repo:7372470516
           echo Testing image: "$TESTING_IMAGE"
-     
           
           docker compose -f ./infra/docker/web/integration-test/docker-compose-test.yml up -d calcom 
 
           echo "Waiting for the server to be healthy..."
           sleep 60s
-          curl --fail localhost:3000/auth/login ||  exit 1
+          
+          response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
 
-          # response=$(curl -o /dev/null -s -w "%{http_code}" localhost:3000)
-          # if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
-          #       echo "Server is healthy"
-               
-          #       exit 0
-          #     fi
-          #     sleep 1
-
-          #   echo "Server health check failed"
-           
-          #   exit 1
+          if [[ "$response" == "200" ]] || [[ "$response" == "307" ]]; then
+          echo "Server is healthy"
+          exit 0
+          fi
+          
+          sleep 1
+          echo "Server health check failed"
+          exit 1
 
 
 
